Please refer to the redux documents on testing. The documents can be found at the following link:

http://rackt.org/redux/docs/recipes/WritingTests.html

When writing client side code, please make sure to test the following:

-Actions: Are your actions sending the proper object?
-Reducers: Are your reducers returning the correct state? 
-Components/Containers: Are you components rendering correctly? Are they initiating the correct actions?
