import Category from '../db/models/category'
import budgetController from './budgetController'

// Private environmental variables
import config from '../env/envConfig'

// Plaid imports
import request from 'request'
import plaid from 'plaid'
import bluebird from 'bluebird'
bluebird.promisifyAll(plaid)

// Twilio Account Variables
const accountSid = config.twilio_private.accountSid
const authToken = config.twilio_private.authToken
const twilioPhone = config.twilio_private.twilioPhone

const client = require('twilio')(accountSid, authToken)

// Plaid Account Variables
const clientId = config.plaid_private.clientId
const secret = config.plaid_private.secret

// Initalize Plaid Client
let plaidClient = new plaid.Client(clientId, secret, plaid.environments.tartan)

let apiController = {

  tradeToken(public_token) {

    // Exchange public token generated by Plaid Link on successful login for Private Plaid token
    return plaidClient.exchangeTokenAsync(public_token)
  },

  setWebhook(plaid_token) {

    // Set webhook which will fire when transaction pulls for user are completed
    plaidClient.patchConnectUser(plaid_token,
    {},
    {
      webhook: 'https://oinkfinancial.com/webhook'
    },
    (err, mfaResponse, response) => {
      // The webhook URI should receive a code 4 "webhook acknowledged" webhook
      // This will get initial state. All accounts and transactions

      if (err) {
        console.error(err)
      }
    })
  },

  retrieveTransactions(plaid_token, userid, cb) {

    // Initial transaction pull recieves all transactions for user and sets up transaction pull webhook
    return plaidClient.getConnectUser(plaid_token,
    {
      webhook: 'https://oinkfinancial.com/webhook'
    },
    (err, response) => {
      if (err) {
        console.error('ERROR', err)
      } else {

        budgetController.updateTransactions(response.transactions, userid).then((response) => {

          // Indicate to plaid call that transactions have been received
          if (cb) {
            // Fire callback if one was passed into recieve transactions
            cb()
          }

          // Check to see if new transactions were updated
          if (response.length > 0) {
            
            // Sum user's budget
            budgetController.updateBudget(userid)
          }
        })
      }
    })
  },

  updateTransactions(plaid_token, userid) {

    // Pull users transactions from last 30 days
    return plaidClient.getConnectUser(plaid_token,
    {
      gte: '30 days ago',
      webhook: 'https://oinkfinancial.com/webhook'
    },
    (err, response) => {
      if (err) {

        // Show error message to developer
        console.error('ERROR', err)
      } else {
        budgetController.updateTransactions(response.transactions, userid).then((response) => {

          // Response will have length > 0 if the user had new transactions that were added to database
          if (response.length > 0) {
            budgetController.findUserByID(userid).then((user) => {

              // Sum user's budget
              budgetController.updateBudget(userid).then(() => {

                // Check to see if user has gone over their total budget if they have selected to recieve text notifications
                if (user[0].phone_verified && user[0].text_over_total) {
                  budgetController.checkTotalMonthlySpending(user[0])
                }

                // Check to see if user has gone over budget in any category if they have selected to recieve text notifications
                if (user[0].phone_verified && user[0].text_over_budget) {
                  budgetController.checkMonthlySpendingByCategory(user[0])
                }
              })
            })
          }
        })
      }
    })
  },

  sendMessage(text, phone) {
    // send message using Twilio API
    client.messages.create({
      to: phone,
      from: twilioPhone,
      body: text,
    }, (err, message) => {
      if (err) {
        console.error(err)
        return err
      } else {
        return message.sid
      }
    })
  },

  getCategories() {
    // Get request for all plaid categories
    request('https://tartan.plaid.com/categories', (error, response, body) => {
      // If successful call
      if (!error && response.statusCode === 200) {
        // Parse body object
        let arr = JSON.parse(body)

        // Remove duplicates
        arr = arr.reduce((acc, item) => {
          if (acc.indexOf(item.hierarchy[0]) === -1) {
            acc.push(item.hierarchy[0])
          }

          return acc
        }, [])

        // Add an Other category for Unknown Transactions
        arr.push('Other')

        // Iterate over array
        bluebird.map(arr, (item) => {
          // Establish search criteria
          let searchCat = new Category({ description: item })

          // Query category table
          return searchCat.fetch().then((cat) => {
            // If category is not on list
            if (!cat) {
              // Add category to db
              return searchCat.save().then((newCat) => {
                // Return new category
                return newCat
              })

            // If category is in table
            } else {
              //Do nothing
              return
            }
          })
        })
      }
    })
  }
}

export default apiController
